[tool.poetry]
package-mode = false
name = "piston-data"
authors = ["ItsNiceCraft <74358857+ItsNiceCraft@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"