name: Collect Piston URLs

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: write


jobs:
    collect:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - uses: snok/install-poetry@v1
            - run: poetry install
            - name: Run collector script
              run: poetry run python3 collect_urls.py
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "chore: update data"
                commit_user_name: itsnicecraft-actions
                commit_user_email: 127137491+itsnicecraft-actions@users.noreply.github.com